"use client"

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Upload, Loader2, History } from "lucide-react"

import { ProtectedRoute } from "@/components/auth/protected-route"
import { ReadmeEditor } from "@/components/readme/readme-editor"

import type React from "react"
import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import {
  GitBranch,
  Check,
  Sparkles,
  Zap,
  Github,
  Code,
  AlertCircle,
} from "lucide-react"
import { Navbar } from "@/components/ui/navbar"
import { motion } from "framer-motion"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { useAuth } from "@/context/auth-context"
import { useGitHubAuth } from "@/context/github-auth-context"
import { RepoPicker, type RepoSelection } from "@/components/repo/repo-picker"
import { ReadmeHistory } from "@/components/readme/readme-history"
import { ReadmeSaver } from "@/components/readme/readme-saver"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"

export default function GenerateReadme() {
  // Example repositories
  const exampleRepos = [
    { name: "React", owner: "facebook/react", icon: <Code className="h-5 w-5" /> },
    { name: "GitFriend", owner: "krishn404/Git-Friend", icon: <Zap className="h-5 w-5" /> },
    { name: "TailwindCSS", owner: "tailwindlabs/tailwindcss", icon: <Sparkles className="h-5 w-5" /> },
  ]

  const [repoUrl, setRepoUrl] = useState("")
  const [generatedReadme, setGeneratedReadme] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [copied, setCopied] = useState(false)
  const [repoData, setRepoData] = useState<{
    name: string
    description: string
    language: string
    stars: number
    forks: number
    owner: string
    created_at?: string
    updated_at?: string
  } | null>(null)
  // Navbar provides theme toggle and auth controls
  const [customRequirements, setCustomRequirements] = useState("")
  const [error, setError] = useState<string | null>(null)
  const [hoverState, setHoverState] = useState({
    card: false,
    button: false,
    examples: Array(exampleRepos.length).fill(false),
  })
  const { isGuest, guestTimeLeft, guestLogout } = useAuth()
  const [showGuestExpired, setShowGuestExpired] = useState(false)
  const [showApplyDialog, setShowApplyDialog] = useState(false)
  const [selectedBranch, setSelectedBranch] = useState("main")
  const [branches, setBranches] = useState<string[]>([])
  const [isApplying, setIsApplying] = useState(false)
  const [applySuccess, setApplySuccess] = useState(false)
  const [showRepoPicker, setShowRepoPicker] = useState(false)
  const [showHistory, setShowHistory] = useState(false)
  
  // Use GitHub auth context
  const { isConnected, accessToken, userInfo, connectGitHub, disconnectGitHub } = useGitHubAuth()

  // Show modal and block actions when guest session expires
  useEffect(() => {
    if (isGuest && guestTimeLeft === 0) {
      setShowGuestExpired(true)
      guestLogout()
    }
  }, [isGuest, guestTimeLeft, guestLogout])

  const validateRepoUrl = (url: string) => {
    // Simple validation for GitHub repository URL
    const githubRegex = /^https?:\/\/github\.com\/[^/]+\/[^/]+\/?$/i
    return githubRegex.test(url)
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && validateRepoUrl(repoUrl)) {
      fetchRepoData()
    }
  }

  // Block API calls and UI actions if guest session expired
  const isGuestBlocked = isGuest && guestTimeLeft === 0

  // Function to fetch branches
  const fetchBranches = async () => {
    if (!accessToken) return
    
    try {
      const response = await fetch("/api/github/branches", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repoUrl, accessToken }),
      })
      
      const data = await response.json()
      if (data.branches) {
        setBranches(data.branches)
        setSelectedBranch(data.branches[0] || "main")
      }
    } catch (error) {
      console.error("Error fetching branches:", error)
    }
  }

  // Function to apply README
  const applyReadmeToGitHub = async () => {
    if (!accessToken) {
      connectGitHub()
      return
    }

    setIsApplying(true)
    try {
      // Add footer to the README content
      const readmeWithFooter = `${generatedReadme}

---

<div align="center">
  <sub>README generated by <a href="https://gitfriend.dev">Git Friend</a> ✨</sub>
</div>
`

      const response = await fetch("/api/apply-readme", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          repoUrl,
          content: readmeWithFooter, // Use the version with footer
          branch: selectedBranch,
          accessToken,
        }),
      })

      const data = await response.json()
      
      if (response.ok) {
        setApplySuccess(true)
        setTimeout(() => {
          setShowApplyDialog(false)
          setApplySuccess(false)
        }, 2000)
      } else {
        throw new Error(data.error || "Failed to apply README")
      }
    } catch (error) {
      console.error("Error applying README:", error)
      alert(error instanceof Error ? error.message : "Failed to apply README")
    } finally {
      setIsApplying(false)
    }
  }

  const fetchRepoData = async (force = false) => {
    if (isGuestBlocked) return
    if (!validateRepoUrl(repoUrl)) {
      setError("Please enter a valid GitHub repository URL")
      return
    }

    setError(null)
    setIsGenerating(true)
    setGeneratedReadme("")
    setRepoData(null)

    try {
      // Extract owner and repo name from URL
      const urlParts = repoUrl.split("/")
      const owner = urlParts[urlParts.length - 2]
      const repo = urlParts[urlParts.length - 1].replace(".git", "")

      // Set initial repo data
      setRepoData({
        name: repo,
        description: "Analyzing repository...",
        language: "Detecting...",
        stars: 0,
        forks: 0,
        owner: owner,
      })

      // Start streaming README generation
      const response = await fetch("/api/generate-readme", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          repoUrl,
          customInstructions: customRequirements || undefined,
          force,
          stream: true, // Request streaming
        }),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: "Failed to start README generation" }))
        throw new Error(errorData.error || "Failed to start README generation")
      }

      // Handle streaming response
      const reader = response.body?.getReader()
      const decoder = new TextDecoder()

      if (!reader) {
        throw new Error("Failed to get response stream")
      }

      let buffer = ""
      let readmeContent = ""

      while (true) {
        const { done, value } = await reader.read()
        if (done) break

        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split("\n\n")
        buffer = lines.pop() || ""

        for (const line of lines) {
          if (line.startsWith("data: ")) {
            const data = line.slice(6)
            if (data === "[DONE]") {
              setIsGenerating(false)
              break
            }
            try {
              const parsed = JSON.parse(data)
              if (parsed.error) {
                throw new Error(parsed.error)
              }
              if (parsed.content) {
                readmeContent += parsed.content
                setGeneratedReadme(readmeContent)
              }
            } catch (e) {
              // Ignore JSON parse errors for incomplete chunks
            }
          }
        }
      }

      setIsGenerating(false)
    } catch (error) {
      console.error("Error generating README:", error)
      setError(error instanceof Error ? error.message : "Failed to generate README")
      setIsGenerating(false)
    }
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedReadme)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadReadme = () => {
    const element = document.createElement("a")
    const file = new Blob([generatedReadme], { type: "text/markdown" })
    element.href = URL.createObjectURL(file)
    element.download = "README.md"
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const handleExampleClick = (repo: string) => {
    setRepoUrl(`https://github.com/${repo}`)
  }

  const handleSelectRepo = (repo: RepoSelection) => {
    setRepoUrl(repo.githubUrl)
    setShowRepoPicker(false)
    setError(null)
  }

  const formatDate = (dateString?: string) => {
    if (!dateString) return "N/A"
    return new Date(dateString).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })
  }

  // Show guest timer at the top if guest
  const guestTimerBar =
    isGuest && guestTimeLeft && guestTimeLeft > 0 ? (
      <div className="w-full bg-yellow-100 text-yellow-800 text-center py-2 font-medium text-sm sticky top-0 z-50">
        Guest access: {Math.floor(guestTimeLeft / 60)}:{(guestTimeLeft % 60).toString().padStart(2, "0")} left.{" "}
        <span className="font-normal">Sign in for unlimited access.</span>
      </div>
    ) : null

  return (
    <ProtectedRoute>
      {guestTimerBar}
      <div className="flex min-h-screen flex-col bg-background text-foreground transition-colors duration-300">
        <ReadmeSaver markdown={generatedReadme} repoUrl={repoUrl} isGenerating={isGenerating} />
        <Navbar />

        {/* Main content */}
        <main className="flex-1 relative pt-24">
          <div className="container max-w-6xl mx-auto py-12">
            <div className="mb-2 flex justify-end">
              <Button variant="outline" size="sm" className="gap-2 rounded-lg border-[hsl(var(--readme-border))] bg-[hsl(var(--readme-card-bg))]" onClick={() => setShowHistory(true)}>
                <History className="h-4 w-4 text-[hsl(var(--readme-primary))]" />
                History
              </Button>
            </div>
            <div className="flex justify-center mb-2">
              <div className="bg-[hsl(var(--readme-primary))/20] text-[hsl(var(--readme-primary))] px-4 py-1.5 rounded-full text-sm font-medium">
                DOCUMENTATION ASSISTANT
              </div>
            </div>

            <motion.div
              className="mb-12 text-center"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
            >
              <h1 className="text-5xl font-bold mb-4">
                <span>Readme</span> <span className="text-[hsl(var(--readme-primary))]">Assistant</span>{" "}
                <span>for Your</span> <span className="text-[hsl(var(--readme-primary))]">Project</span>
              </h1>
              <p className="text-[hsl(var(--readme-text-muted))] max-w-2xl mx-auto text-lg">
                Enter a GitHub repository URL and let Git Friend analyze your codebase to generate professional
                documentation in seconds.
              </p>
            </motion.div>

            {error && (
              <motion.div
                className="max-w-3xl mx-auto mb-6"
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3 }}
              >
                <Alert variant="destructive">
                  <AlertCircle className="h-4 w-4" />
                  <AlertTitle>Error</AlertTitle>
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              </motion.div>
            )}

            <motion.div
              className="max-w-3xl mx-auto mb-8"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              onMouseEnter={() => setHoverState((prev) => ({ ...prev, card: true }))}
              onMouseLeave={() => setHoverState((prev) => ({ ...prev, card: false }))}
            >
              <Card
                className={`border-[hsl(var(--readme-border))] bg-[hsl(var(--readme-card-bg))] shadow-lg overflow-hidden transition-all duration-300 ${
                  hoverState.card ? "shadow-xl border-[hsl(var(--readme-primary))/30]" : ""
                }`}
              >
                <CardContent className="p-8">
                  <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-2">
                      <div className="h-10 w-10 rounded-full bg-[hsl(var(--readme-primary))/20] flex items-center justify-center">
                        <GitBranch className="h-5 w-5 text-[hsl(var(--readme-primary))]" />
                      </div>
                      <span className="text-xl font-medium">Generate Your README</span>
                    </div>
                  </div>

                  <p className="text-[hsl(var(--readme-text-muted))] text-sm mb-6">
                    Enter a GitHub repository URL to analyze code and generate a detailed README file that explains what
                    your project does, why it exists, and how to use it.
                  </p>

                  <div className="relative mb-3 group">
                    <div className="absolute inset-0 rounded-md -m-1 bg-gradient-to-r from-[hsl(var(--readme-primary))/0] via-[hsl(var(--readme-primary))/50] to-[hsl(var(--readme-primary))/0] opacity-0 group-hover:opacity-100 transition-opacity blur-md"></div>
                    <div className="absolute left-3 top-1/2 -translate-y-1/2 text-[hsl(var(--readme-text-muted))]">
                      <Github className="h-5 w-5" />
                    </div>
                    <input
                      className="w-full h-12 bg-[hsl(var(--readme-card-bg))] border border-[hsl(var(--readme-border))] rounded-md px-10 py-2 text-[hsl(var(--readme-text))] placeholder:text-[hsl(var(--readme-text-muted))] focus:outline-none focus:ring-1 focus:ring-[hsl(var(--readme-primary))] relative"
                      placeholder="https://github.com/username/repository"
                      value={repoUrl}
                      onChange={(e) => {
                        setRepoUrl(e.target.value)
                        // Auto-start generation when valid URL is pasted
                        if (validateRepoUrl(e.target.value) && !isGenerating && !generatedReadme) {
                          setTimeout(() => fetchRepoData(false), 500) // Small delay to allow paste to complete
                        }
                      }}
                      onKeyDown={handleKeyDown}
                    />
                  </div>

                  <div className="mb-6 flex justify-end">
                    <Button variant="outline" size="sm" onClick={() => setShowRepoPicker(true)}>
                      Browse your repositories
                    </Button>
                  </div>

                  <div className="flex justify-end gap-2">
                    <Button
                      className={`bg-[hsl(var(--readme-primary))] hover:bg-[hsl(var(--readme-primary-hover))] text-[hsl(var(--readme-primary-foreground))] px-6 py-2 rounded-md flex items-center gap-2 transition-all duration-300 ${
                        hoverState.button ? "shadow-lg shadow-[hsl(var(--readme-primary))/20] scale-105" : ""
                      }`}
                      onClick={() => fetchRepoData(false)}
                      disabled={isGenerating || !repoUrl}
                      onMouseEnter={() => setHoverState((prev) => ({ ...prev, button: true }))}
                      onMouseLeave={() => setHoverState((prev) => ({ ...prev, button: false }))}
                    >
                      {isGenerating ? (
                        <>
                          <motion.div
                            animate={{ rotate: 360 }}
                            transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                            className="h-4 w-4 border-2 border-current border-t-transparent rounded-full"
                          />
                          Generating...
                        </>
                      ) : (
                        <>
                          <Zap className="h-4 w-4" />
                          Generate README
                        </>
                      )}
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </motion.div>

            {/* Example repositories */}
            {!generatedReadme && !isGenerating && (
              <motion.div
                className="max-w-3xl mx-auto mb-16"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.2 }}
              >
                <h3 className="text-lg font-medium mb-4 text-center">Try with popular repositories</h3>
                <div className="grid grid-cols-3 gap-4">
                  {exampleRepos.map((repo, index) => (
                    <Card
                      key={index}
                      className={`border-[hsl(var(--readme-border))] bg-[hsl(var(--readme-card-bg))] cursor-pointer hover:bg-[hsl(var(--readme-bg))] transition-all duration-300 ${
                        hoverState.examples[index]
                          ? "shadow-md border-[hsl(var(--readme-primary))/30] scale-[1.02]"
                          : ""
                      }`}
                      onClick={() => handleExampleClick(repo.owner)}
                      onMouseEnter={() => {
                        const newExamples = [...hoverState.examples]
                        newExamples[index] = true
                        setHoverState((prev) => ({ ...prev, examples: newExamples }))
                      }}
                      onMouseLeave={() => {
                        const newExamples = [...hoverState.examples]
                        newExamples[index] = false
                        setHoverState((prev) => ({ ...prev, examples: newExamples }))
                      }}
                    >
                      <CardContent className="p-4 flex items-center gap-3">
                        <div className="h-10 w-10 rounded-full bg-[hsl(var(--readme-primary))/20] flex items-center justify-center">
                          {repo.icon}
                        </div>
                        <div>
                          <div className="font-medium">{repo.name}</div>
                          <div className="text-xs text-[hsl(var(--readme-text-muted))]">{repo.owner}</div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </motion.div>
            )}

            {generatedReadme && (
              <motion.div className="mx-auto max-w-7xl" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
                <ReadmeEditor
                  markdown={generatedReadme}
                  onChange={setGeneratedReadme}
                  onDownload={downloadReadme}
                  onCopy={copyToClipboard}
                  copied={copied}
                  onNew={() => { setRepoUrl(""); setGeneratedReadme(""); setRepoData(null) }}
                  onRegenerate={() => fetchRepoData(true)}
                  canRegenerate={!isGenerating && !!repoUrl}
                  onApply={() => { if (!isConnected) { connectGitHub(); return }; setShowApplyDialog(true); fetchBranches() }}
                  applyLabel={isConnected ? "Apply to GitHub" : "Connect GitHub"}
                />
              </motion.div>
            )}
          </div>

          {/* Show streaming README as it's being generated */}
          {isGenerating && !generatedReadme && (
            <motion.div
              className="max-w-5xl mx-auto"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
            >
              <Card className="border-[hsl(var(--readme-border))] bg-[hsl(var(--readme-card-bg))] shadow-lg">
                <CardContent className="p-8">
                  <div className="flex items-center justify-center gap-3 mb-4">
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                      className="h-6 w-6 border-2 border-[hsl(var(--readme-primary))] border-t-transparent rounded-full"
                    />
                    <span className="text-lg font-medium">Generating README...</span>
                  </div>
                  <p className="text-center text-[hsl(var(--readme-text-muted))] text-sm">
                    Analyzing your repository and creating documentation
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Apply to GitHub Dialog */}
          <Dialog open={showApplyDialog} onOpenChange={setShowApplyDialog}>
            <DialogContent className="sm:max-w-md">
              <DialogHeader>
                <DialogTitle>Apply README to GitHub</DialogTitle>
                <DialogDescription>
                  This will create or update the README.md file in your repository.
                </DialogDescription>
              </DialogHeader>
              
              {applySuccess ? (
                <div className="flex flex-col items-center justify-center py-6">
                  <div className="h-12 w-12 rounded-full bg-muted flex items-center justify-center mb-4">
                    <Check className="h-6 w-6 text-foreground" />
                  </div>
                  <p className="text-lg font-medium">README Applied Successfully!</p>
                  <p className="text-sm text-muted-foreground mt-2">
                    Check your repository to see the changes.
                  </p>
                </div>
              ) : (
                <>
                  <div className="space-y-4 py-4">
                    <div className="space-y-2">
                      <label className="text-sm font-medium">Repository</label>
                      <p className="text-sm text-muted-foreground">{repoUrl}</p>
                    </div>
                    
                    <div className="space-y-2">
                      <label className="text-sm font-medium">Target Branch</label>
                      <Select value={selectedBranch} onValueChange={setSelectedBranch}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select a branch" />
                        </SelectTrigger>
                        <SelectContent>
                          {branches.map((branch) => (
                            <SelectItem key={branch} value={branch}>
                              {branch}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    
                    <div className="rounded-lg bg-muted p-3 text-sm">
                      <p className="font-medium mb-1">⚠️ Important</p>
                      <p className="text-muted-foreground">
                        This will create a new commit with the message "docs: Update README.md via Git Friend"
                      </p>
                    </div>
                  </div>
                  
                  <DialogFooter>
                    <Button
                      variant="outline"
                      onClick={() => setShowApplyDialog(false)}
                      disabled={isApplying}
                    >
                      Cancel
                    </Button>
                    <Button
                      onClick={applyReadmeToGitHub}
                      disabled={isApplying}
                      className="bg-[hsl(var(--readme-primary))] hover:bg-[hsl(var(--readme-primary-hover))]"
                    >
                      {isApplying ? (
                        <>
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                          Applying...
                        </>
                      ) : (
                        <>
                          <Upload className="mr-2 h-4 w-4" />
                          Apply README
                        </>
                      )}
                    </Button>
                  </DialogFooter>
                </>
              )}
            </DialogContent>
          </Dialog>
          <Dialog open={showRepoPicker} onOpenChange={setShowRepoPicker}>
            <DialogContent className="max-w-2xl">
              <DialogHeader>
                <DialogTitle>Select a repository</DialogTitle>
                <DialogDescription>Browse connected GitHub repositories or paste a URL.</DialogDescription>
              </DialogHeader>
              <RepoPicker onSelect={handleSelectRepo} actionLabel="Select" />
            </DialogContent>
          </Dialog>
          <Sheet open={showHistory} onOpenChange={setShowHistory}>
            <SheetContent side="right" className="w-full border-l border-[hsl(var(--readme-border))] bg-[hsl(var(--readme-card-bg))] p-0 sm:max-w-md">
              <SheetHeader className="border-b border-[hsl(var(--readme-border))] px-6 py-5">
                <SheetTitle className="flex items-center gap-2"><History className="h-4 w-4 text-[hsl(var(--readme-primary))]" />Your READMEs</SheetTitle>
                <SheetDescription>Open and manage your saved README sessions.</SheetDescription>
              </SheetHeader>
              <div className="h-[calc(100vh-105px)] p-4">
                <ReadmeHistory onOpen={(_id, markdown, url) => { setRepoUrl(url); setGeneratedReadme(markdown); setRepoData(null); setShowHistory(false) }} />
              </div>
            </SheetContent>
          </Sheet>
        </main>
      </div>
      
      {/* Guest session expired modal */}
      {showGuestExpired && (
        <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center">
          <div className="bg-white rounded-lg shadow-lg p-8 max-w-sm w-full text-center">
            <h2 className="text-xl font-bold mb-2">Guest Session Expired</h2>
            <p className="mb-4 text-gray-600">
              Your 5-minute guest session has ended. Please sign in to continue using Git Friend.
            </p>
            <Button onClick={() => window.location.reload()} className="w-full">
              Sign In
            </Button>
          </div>
        </div>
      )}
    </ProtectedRoute>
  )
}
