"use client"

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Upload, Loader2, Check } from "lucide-react"

import { ProtectedRoute } from "@/components/auth/protected-route"
import { InitialInputStage } from "@/components/readme/initial-input-stage"
import { ReadmeWorkspace } from "@/components/readme/readme-workspace"

import type React from "react"
import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Navbar } from "@/components/ui/navbar"
import { useAuth } from "@/context/auth-context"
import { useGitHubAuth } from "@/context/github-auth-context"

export default function GenerateReadme() {
  const [repoUrl, setRepoUrl] = useState("")
  const [generatedReadme, setGeneratedReadme] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [copied, setCopied] = useState(false)
  const [repoData, setRepoData] = useState<{
    name: string
    description: string
    language: string
    stars: number
    forks: number
    owner: string
    created_at?: string
    updated_at?: string
  } | null>(null)
  const [customRequirements, setCustomRequirements] = useState("")
  const [error, setError] = useState<string | null>(null)
  const { isGuest, guestTimeLeft, guestLogout } = useAuth()
  const [showGuestExpired, setShowGuestExpired] = useState(false)
  const [showApplyDialog, setShowApplyDialog] = useState(false)
  const [selectedBranch, setSelectedBranch] = useState("main")
  const [branches, setBranches] = useState<string[]>([])
  const [isApplying, setIsApplying] = useState(false)
  const [applySuccess, setApplySuccess] = useState(false)
  
  // Use GitHub auth context
  const { isConnected, accessToken, userInfo, connectGitHub, disconnectGitHub } = useGitHubAuth()

  // Show modal and block actions when guest session expires
  useEffect(() => {
    if (isGuest && guestTimeLeft === 0) {
      setShowGuestExpired(true)
      guestLogout()
    }
  }, [isGuest, guestTimeLeft, guestLogout])

  const validateRepoUrl = (url: string) => {
    // Simple validation for GitHub repository URL
    const githubRegex = /^https?:\/\/github\.com\/[^/]+\/[^/]+\/?$/i
    return githubRegex.test(url)
  }

  // Block API calls and UI actions if guest session expired
  const isGuestBlocked = isGuest && guestTimeLeft === 0

  // Function to fetch branches
  const fetchBranches = async () => {
    if (!accessToken) return
    
    try {
      const response = await fetch("/api/github/branches", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repoUrl, accessToken }),
      })
      
      const data = await response.json()
      if (data.branches) {
        setBranches(data.branches)
        setSelectedBranch(data.branches[0] || "main")
      }
    } catch (error) {
      console.error("Error fetching branches:", error)
    }
  }

  // Function to apply README
  const applyReadmeToGitHub = async () => {
    if (!accessToken) {
      connectGitHub()
      return
    }

    setIsApplying(true)
    try {
      // Add footer to the README content
      const readmeWithFooter = `${generatedReadme}

---

<div align="center">
  <sub>README generated by <a href="https://gitfriend.dev">Git Friend</a> ✨</sub>
</div>
`

      const response = await fetch("/api/apply-readme", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          repoUrl,
          content: readmeWithFooter, // Use the version with footer
          branch: selectedBranch,
          accessToken,
        }),
      })

      const data = await response.json()
      
      if (response.ok) {
        setApplySuccess(true)
        setTimeout(() => {
          setShowApplyDialog(false)
          setApplySuccess(false)
        }, 2000)
      } else {
        throw new Error(data.error || "Failed to apply README")
      }
    } catch (error) {
      console.error("Error applying README:", error)
      alert(error instanceof Error ? error.message : "Failed to apply README")
    } finally {
      setIsApplying(false)
    }
  }

  const fetchRepoData = async (force = false) => {
    if (isGuestBlocked) return
    if (!validateRepoUrl(repoUrl)) {
      setError("Please enter a valid GitHub repository URL")
      return
    }

    setError(null)
    setIsGenerating(true)
    setGeneratedReadme("")
    setRepoData(null)

    try {
      // Extract owner and repo name from URL
      const urlParts = repoUrl.split("/")
      const owner = urlParts[urlParts.length - 2]
      const repo = urlParts[urlParts.length - 1].replace(".git", "")

      // Set initial repo data
      setRepoData({
        name: repo,
        description: "Analyzing repository...",
        language: "Detecting...",
        stars: 0,
        forks: 0,
        owner: owner,
      })

      // Start streaming README generation
      const response = await fetch("/api/generate-readme", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          repoUrl,
          customInstructions: customRequirements || undefined,
          force,
          stream: true, // Request streaming
        }),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: "Failed to start README generation" }))
        throw new Error(errorData.error || "Failed to start README generation")
      }

      // Handle streaming response
      const reader = response.body?.getReader()
      const decoder = new TextDecoder()

      if (!reader) {
        throw new Error("Failed to get response stream")
      }

      let buffer = ""
      let readmeContent = ""

      while (true) {
        const { done, value } = await reader.read()
        if (done) break

        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split("\n\n")
        buffer = lines.pop() || ""

        for (const line of lines) {
          if (line.startsWith("data: ")) {
            const data = line.slice(6)
            if (data === "[DONE]") {
              setIsGenerating(false)
              break
            }
            try {
              const parsed = JSON.parse(data)
              if (parsed.error) {
                throw new Error(parsed.error)
              }
              if (parsed.content) {
                readmeContent += parsed.content
                setGeneratedReadme(readmeContent)
              }
            } catch (e) {
              // Ignore JSON parse errors for incomplete chunks
            }
          }
        }
      }

      setIsGenerating(false)
    } catch (error) {
      console.error("Error generating README:", error)
      setError(error instanceof Error ? error.message : "Failed to generate README")
      setIsGenerating(false)
    }
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedReadme)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadReadme = () => {
    const element = document.createElement("a")
    const file = new Blob([generatedReadme], { type: "text/markdown" })
    element.href = URL.createObjectURL(file)
    element.download = "README.md"
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const handleAIAction = async (action: string, selectedText: string): Promise<string> => {
    try {
      const response = await fetch("/api/readme/refine-text", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action, // 'shorten', 'expand', 'rephrase', 'refine'
          text: selectedText,
        }),
      })

      if (!response.ok) {
        throw new Error("Failed to refine text")
      }

      const data = await response.json()
      return data.refinedText || selectedText
    } catch (error) {
      console.error("AI action error:", error)
      throw error
    }
  }

  // Show guest timer at the top if guest
  const guestTimerBar =
    isGuest && guestTimeLeft && guestTimeLeft > 0 ? (
      <div className="w-full bg-yellow-100 text-yellow-800 text-center py-2 font-medium text-sm sticky top-0 z-50">
        Guest access: {Math.floor(guestTimeLeft / 60)}:{(guestTimeLeft % 60).toString().padStart(2, "0")} left.{" "}
        <span className="font-normal">Sign in for unlimited access.</span>
      </div>
    ) : null

  // Phase-based state: 'initial' | 'workspace'
  const phase = generatedReadme ? "workspace" : "initial"

  return (
    <ProtectedRoute>
      {guestTimerBar}
      {phase === "initial" ? (
        // Phase 1: Initial Input Stage
        <div className="flex min-h-screen flex-col bg-background text-foreground">
          <Navbar />
          <main className="flex-1 flex items-center justify-center pt-16">
            <InitialInputStage
              onSubmit={(url) => {
                setRepoUrl(url)
                fetchRepoData(false)
              }}
              isLoading={isGenerating}
              error={error}
            />
          </main>
        </div>
      ) : (
        // Phase 2: Workspace with split-screen
        <div className="flex min-h-screen flex-col bg-background text-foreground">
          <Navbar />
          <main className="flex-1 overflow-hidden">
            <ReadmeWorkspace
              repoUrl={repoUrl}
              markdown={generatedReadme}
              onMarkdownChange={(newMarkdown) => {
                setGeneratedReadme(newMarkdown)
              }}
              onCopy={copyToClipboard}
              onDownload={downloadReadme}
              onNew={() => {
                setRepoUrl("")
                setGeneratedReadme("")
                setRepoData(null)
              }}
              onRegenerate={() => fetchRepoData(true)}
              onApply={() => {
                if (!isConnected) {
                  connectGitHub()
                  return
                }
                setShowApplyDialog(true)
                fetchBranches()
              }}
              copied={copied}
              canRegenerate={!isGenerating && !!repoUrl}
              isGenerating={isGenerating}
              onAIAction={handleAIAction}
            />
          </main>
        </div>
      )}



      {/* Apply to GitHub Dialog - outside of phase structure */}
      <Dialog open={showApplyDialog} onOpenChange={setShowApplyDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Apply README to GitHub</DialogTitle>
            <DialogDescription>
              This will create or update the README.md file in your repository.
            </DialogDescription>
          </DialogHeader>
          
          {applySuccess ? (
            <div className="flex flex-col items-center justify-center py-6">
              <div className="h-12 w-12 rounded-full bg-green-100 dark:bg-green-900 flex items-center justify-center mb-4">
                <Check className="h-6 w-6 text-green-600 dark:text-green-400" />
              </div>
              <p className="text-lg font-medium">README Applied Successfully!</p>
              <p className="text-sm text-muted-foreground mt-2">
                Check your repository to see the changes.
              </p>
            </div>
          ) : (
            <>
              <div className="space-y-4 py-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Repository</label>
                  <p className="text-sm text-muted-foreground">{repoUrl}</p>
                </div>
                
                <div className="space-y-2">
                  <label className="text-sm font-medium">Target Branch</label>
                  <Select value={selectedBranch} onValueChange={setSelectedBranch}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select a branch" />
                    </SelectTrigger>
                    <SelectContent>
                      {branches.map((branch) => (
                        <SelectItem key={branch} value={branch}>
                          {branch}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                
                <div className="rounded-lg bg-muted p-3 text-sm">
                  <p className="font-medium mb-1">⚠️ Important</p>
                  <p className="text-muted-foreground">
                    This will create a new commit with the message "docs: Update README.md via Git Friend"
                  </p>
                </div>
              </div>
              
              <DialogFooter>
                <Button
                  variant="outline"
                  onClick={() => setShowApplyDialog(false)}
                  disabled={isApplying}
                >
                  Cancel
                </Button>
                <Button
                  onClick={applyReadmeToGitHub}
                  disabled={isApplying}
                  className="bg-[hsl(var(--readme-primary))] hover:bg-[hsl(var(--readme-primary-hover))]"
                >
                  {isApplying ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Applying...
                    </>
                  ) : (
                    <>
                      <Upload className="mr-2 h-4 w-4" />
                      Apply README
                    </>
                  )}
                </Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>
      
      {/* Guest session expired modal */}
      {showGuestExpired && (
        <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center">
          <div className="bg-white rounded-lg shadow-lg p-8 max-w-sm w-full text-center">
            <h2 className="text-xl font-bold mb-2">Guest Session Expired</h2>
            <p className="mb-4 text-gray-600">
              Your 5-minute guest session has ended. Please sign in to continue using Git Friend.
            </p>
            <Button onClick={() => window.location.reload()} className="w-full">
              Sign In
            </Button>
          </div>
        </div>
      )}
    </ProtectedRoute>
  )
}
